### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by datalater** [CodeSoom/project-react-3-datalater#1]
# 프로젝트

## 01 이 앱을 언제 사용하나요?

친구와 약속을 정할 때 중간지점을 알아내기 위해 사용합니다.

## 02 제약 조건은 무엇인가요?

친구의 수를 3명으로 제한합니다.

## 03 구체적인 사례는 무엇인가요?

정자역과 잠실역의 중간지점을 구합니다. 복정역이 나옵니다.

## 04 이번주에 구현할 기능을 우선 순위대로 작성해주세요.

- [x] 사용자가 직접 찾을 수 있도록 지도 사이트를 링크한다.
- [x] 지도를 띄운다. 
- [ ] 출발지점을 마킹할 수 있도록 한다. => next

참고로 중간지점을 구하는 알고리즘은 아직 구현되지 않았으므로 사용자가 눈 대중으로 찾을 수 있게 지도를 연결합니다.

# 학습

[Notion Page](https://www.notion.so/jayday/9-1d5c029712d84b7f94383eccffe83831)

**Comment by moonkii** [comment]
![image](https://user-images.githubusercontent.com/46776329/112727002-a522fd00-8f63-11eb-883f-ac8b167e61bd.png)

의문점에 대해 스스로 정리하고 답을 찾아보려고하는 시도가 좋은 것 같아요!

script 로 불러오는 SDK 를 따로 모듈화 시켜서 사용하지 않는 이상 글로벌로 사용할 수 밖에 없어요.(만약 한다고 해도 이렇게 까지 굳이 라는 생각이...)
다만, 글로벌로 사용하는 SDK 들만 따로 모아 `init()` 함수 등을 만들어 따로 처리해준다든지 파일로 분리해서 명확하게 구분해주면 관리하기가 좋을 것 같아요. 그렇게 해서 해당 파일 등에서 대해서만 ESLint 예외를 추가해주는식으로 하면 되겠네요 ;)

**Comment by datalater** [comment]
크 소중한 리뷰 남겨주셔서 감사합니다!!

**Comment by datalater** [comment]
# 회고 작성

[9주차 주간 회고](https://www.notion.so/jayday/9-3bcda666a4534572abae877d74ff532c)

**Comment by datalater** [comment]
![image](https://user-images.githubusercontent.com/8105528/116804788-9b8d4600-ab5c-11eb-92c2-c3a816eedd84.png)
