### ISSUE TITLE
README 도 업데이트 해주세요!

### ISSUE THREAD

**Issue by moonkii** [CodeSoom/project-react-3-datalater#6]
프로젝트에 대한 설명이나 프로그램 작동 방법 등에 대해 `README` 도 진행상황에 따라 함께 업데이트해주면 좋을 것 같아요!

오픈소스 프로젝트 등의 README 를 참고해보시면 도움이 될거에요!

**Comment by datalater** [comment]
> 프로젝트에 대한 설명이나 프로그램 작동 방법 등에 대해 `README` 도 진행상황에 따라 함께 업데이트해주면 좋을 것 같아요!
> 
> 오픈소스 프로젝트 등의 README 를 참고해보시면 도움이 될거에요!

그렇군요ㅎㅎㅎ 감사합니다!
