### ISSUE TITLE
2주차 진행

### ISSUE THREAD

**Issue by datalater** [CodeSoom/project-react-3-datalater#7]
# 프로젝트

## 01 이 앱을 언제 사용하나요?

사용자는 친구와 약속을 정할 때 중간지점을 알고 싶을 때 사용합니다.

## 02 제약 조건은 무엇인가요?

친구의 수를 3명으로 제한합니다.

## 03 구체적인 사례는 무엇인가요?

정자역과 잠실역의 중간지점을 구합니다. 복정역이 나옵니다.

## 04 이번주에 구현할 기능을 우선 순위대로 작성해주세요.

- [x] 출발지점을 검색해서 입력 받는 form을 보여준다.
- [x] 출발지점을 입력 받으면 좌표를 얻는다.
- [ ] 출발지점을 두 개 받으면 중간지점을 알려준다.

## 05 그외 필요한 작업을 작성해주세요.

- [x] README.md 작성
- [x] CI에 CNAME 추가하기

# 진행상황

[Notion Page](https://www.notion.so/jayday/10-d80e2539ceb24762a635a8f586fd6f00)

# 회고

[주간 회고](https://www.notion.so/jayday/10-5b66d0113f6a48de8363d4ed254c37e4)

**Comment by Kihyun92** [comment]
진행 상황을 한번 체크해보신게 좋네요! 나중에 돌아봤을때 매주 어떤 작업들을 했는지 알기 좋을 것 같아요 👍🏼 

우선 순위에 따라 작업도 잘 나눠보신 것 같습니다. 이번주도 화이팅입니다~🏃🏻‍♂️

**Comment by datalater** [comment]
# onChange 이벤트가 제대로 작동하지 않는 이유 해결

- React 컴포넌트가 통째로 duplicate 되어 store도 중복으로 생겼고 그로 인해 dispatch가 제대로 전달되지 않았기 때문이었다.
- React 컴포넌트가 통째로 duplicate 된 이유는 html-webpack-plugin 사용시 template으로 사용한 html 파일에 스크립트 로딩 코드(`<script src="/main.js" />`)가 있었기 때문이었다. 놀랍게도 html-webpack-plugin은 웹팩으로 빌드한 스크립트를 자동으로 불러온다. 따라서 template 파일에 로딩 스크립트가 있을 경우 중복이 된다.
- 컴포넌트 코드가 잘못된 줄 알고 코드만 계속 디버깅했다. 이것 때문에 무려 월요일, 화요일 동안 6시간을 삽질했다. 아오...

<img width="683" alt="Screen Shot 2021-03-30 at 12 53 51" src="https://user-images.githubusercontent.com/8105528/112935331-83da3080-915e-11eb-9af1-46412330a9a0.png">

**Comment by Kihyun92** [comment]
트러블 슈팅 과정을 잘 정리해주셨네요 💯 

문제를 찾는 과정이 쉽지 않았을 텐데 고생하셨습니다🙏

슬랙 채널에 공유해보시면 좋을 것 같아요! 다른 동료들에게 도움이 될 것 같아요 ㅎㅎ

**Comment by datalater** [comment]
# 회고

[주간 회고](https://www.notion.so/jayday/10-5b66d0113f6a48de8363d4ed254c37e4)
